name: Testing on Mac, Linux and Windows

on:
  push:
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Testing Linux Installation
        run: |
          bash nvim_app.sh --pipeline
 
  test-macOS:
    runs-on: macos-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      
      - name: Uninstall Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
          sudo rm -rf /opt/homebrew
          sudo rm -rf /usr/local/Homebrew
          rm -rf ~/Library/Caches/Homebrew

      - name: Testing MacOS Installation
        run: |
          bash nvim_app.sh --pipeline

